site_name: Projector documentation

# Repository (add link to repository in header)
# TODO: rename to "projector"?
repo_name: JetBrains/projector-client
# TODO: rename to "projector"?
repo_url: https://github.com/JetBrains/projector-client
edit_uri: edit/master/docSrc/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2019-2022 JetBrains s.r.o.'

theme:
  name: material
  favicon: favicon.svg
  logo: favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
  palette:
    primary: white

extra:
  social:
    - icon: fontawesome/brands/github
      # TODO: rename to "projector"?
      link: https://github.com/JetBrains/projector-client
    - icon: fontawesome/brands/telegram
      link: https://t.me/JBProjector
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ProjectorJB
    - icon: fontawesome/solid/globe
      link: https://projector.jetbrains.com

plugins:
  - search

# TODO: do we need it?
#       Besides basic page views, site search can also be tracked to understand better how people
#       use your documentation and what they expect to find.
# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

# Dev server binding
dev_addr: 0.0.0.0:8000

nav:
  - Home: index.md
  - User guide – IntelliJ IDEs:
      - JetBrains IDEs: ij_user_guide/jetbrains.md
      - Running remote app – servers: ij_user_guide/running.md
      - Accessing remote app – clients: ij_user_guide/accessing.md
      - Customizing servers: ij_user_guide/server_customization.md
      - Android: ij_user_guide/android.md
  - User guide – other Swing apps:
      - Arbitrary Swing app: swing_user_guide/arbitrary.md
  - Developer guide:
      - Ecosystem: dev_guide/ecosystem.md
      - Projector ClassLoader: dev_guide/classloader.md
      - Academic works: dev_guide/works.md
  - About:
      - Comparison to other remote access solutions: about/comparison.md
      - Use cases: about/usecases.md
      - Versions: about/versions.md
      - Contributing: about/contributing.md
      - Code of conduct: about/coc.md
