name: Upload Release Asset (launcher)

on:
  push:
    tags:
      - "launcher-v*"

jobs:
  main:
    name: Upload Release Asset (launcher)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: sudo apt update && sudo apt install wine-stable -y
      - name: Build project
        run: ./gradlew :projector-launcher:distZip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: Changelog is available in [CHANGELOG.md](https://github.com/JetBrains/projector-client/blob/master/projector-launcher/CHANGELOG.md).
      - name: Tag name  # Inspired from https://github.community/t/how-to-get-just-the-tag-name/16241/11
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Upload Release Asset (darwin-x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: projector-launcher/build/electronOut/projector-darwin-x64.zip
          asset_name: projector-darwin-x64-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (darwin-arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: projector-launcher/build/electronOut/projector-darwin-arm64.zip
          asset_name: projector-darwin-arm64-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (linux-x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: projector-launcher/build/electronOut/projector-linux-x64.zip
          asset_name: projector-linux-x64-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (win32-x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: projector-launcher/build/electronOut/projector-win32-x64.zip
          asset_name: projector-win32-x64-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
          asset_content_type: application/zip
